packages:
  - appviews
  - dash/*
  - site
  - shared/*
  - storybook
  - smoke
  - admin
  - admin-new

onlyBuiltDependencies:
  - core-js-pure
  - cypress
  - esbuild
  - nx
  - puppeteer
  - sharp
