// generated by @kiahjh, edit at will

import type { SuccessOutput } from '../shared';

export namespace HollandTalkSubscription {
  export interface Input {
    email: string;
  }

  export type Output = SuccessOutput;
}
