// generated by Kiah, edit at will
import type { SuccessOutput } from '../shared';
import type { ReleaseChannel } from '../../named';

export namespace SaveDevice {
  export interface Input {
    id: UUID;
    name?: string;
    releaseChannel: ReleaseChannel;
  }

  export type Output = SuccessOutput;
}
