[build]
  publish = "out/"
  ignore = "false"
  command = """
  cd ../../ && \
	pnpm --filter site build && \
  cp site/_redirects site/out
  """

# removed    pnpm --filter site export && \


[[redirects]]
  from = "/support" # in case i entered the url wrong somewhere...
  to = "/contact"
  status = 200

[build.environment]
  NODE_VERSION = "16.17.1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = "frame-ancestors 'none'"
