[build]
  publish = "build/"
  command = "pnpm build"
  ignore = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_API_ENDPOINT = 'https://api.gertrude.app'

[context.deploy-preview.environment]
  VITE_IS_STAGING = 'true'
  VITE_TEST_ADMIN_CREDS = 'be000000-0000-0000-0000-000000000000:be000000-0000-0000-0000-000000000000'
  VITE_API_ENDPOINT= 'https://api--staging.gertrude.app'

