[build]
  publish = "build/"
  command = "cd ../../ && make build-dash"
  ignore = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  SNOWPACK_PUBLIC_GRAPHQL_ENDPOINT = 'https://api.gertrude-app.com/graphql/dashboard'

[context.deploy-preview.environment]
  SNOWPACK_PUBLIC_IS_STAGING = 'true'
  SNOWPACK_PUBLIC_TEST_ADMIN_CREDS = 'BE000000-0000-0000-0000-000000000000:BE000000-0000-0000-0000-000000000000'
  SNOWPACK_PUBLIC_GRAPHQL_ENDPOINT = 'https://api--staging.gertrude-app.com/graphql/dashboard'

