mv ./src/pages/docs/basics-of-time-travel.md ./src/pages/docs/basics-of-time-travel.mdx
mv ./src/pages/docs/writing-plugins.md ./src/pages/docs/writing-plugins.mdx
mv ./src/pages/docs/predicting-user-behavior.md ./src/pages/docs/predicting-user-behavior.mdx
mv ./src/pages/docs/design-principles.md ./src/pages/docs/design-principles.mdx
mv ./src/pages/docs/compile-time-caching.md ./src/pages/docs/compile-time-caching.mdx
mv ./src/pages/docs/temporal-paradoxes.md ./src/pages/docs/temporal-paradoxes.mdx
mv ./src/pages/docs/cacheadvance-predict.md ./src/pages/docs/cacheadvance-predict.mdx
mv ./src/pages/docs/neuralink-integration.md ./src/pages/docs/neuralink-integration.mdx
mv ./src/pages/docs/predictive-data-generation.md ./src/pages/docs/predictive-data-generation.mdx
mv ./src/pages/docs/cacheadvance-flush.md ./src/pages/docs/cacheadvance-flush.mdx
mv ./src/pages/docs/introduction-to-string-theory.md ./src/pages/docs/introduction-to-string-theory.mdx
mv ./src/pages/docs/cacheadvance-regret.md ./src/pages/docs/cacheadvance-regret.mdx
mv ./src/pages/docs/cacheadvance-revert.md ./src/pages/docs/cacheadvance-revert.mdx
mv ./src/pages/docs/understanding-caching.md ./src/pages/docs/understanding-caching.mdx
mv ./src/pages/docs/architecture-guide.md ./src/pages/docs/architecture-guide.mdx
mv ./src/pages/docs/how-to-contribute.md ./src/pages/docs/how-to-contribute.mdx
mv ./src/pages/docs/installation.md ./src/pages/docs/installation.mdx
mv ./src/pages/docs/the-butterfly-effect.md ./src/pages/docs/the-butterfly-effect.mdx
