name: ci

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install pnpm
        uses: pnpm/action-setup@v2
      - name: install deps
        run: pnpm install
      - name: lint
        run: make lint
      - name: format
        run: make format-check
      - name: typecheck
        run: make ts-check
      - name: test
        run: make test
      - name: reset staging
        run: curl --silent ${{ secrets.STAGING_API_RESET_ROUTE  }}; true

  storybook:
    name: storybook
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install pnpm
        uses: pnpm/action-setup@v2
      - name: install deps
        run: pnpm install
      - name: build storybook
        run: make build-storybook

  dashboard:
    name: dashboard
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install pnpm
        uses: pnpm/action-setup@v2
      - name: install deps
        run: pnpm install
      - name: build dashboard
        run: make build-dash

  marketing:
    name: marketing
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install pnpm
        uses: pnpm/action-setup@v2
      - name: install deps
        run: pnpm install
      - name: build marketing
        run: make build-marketing

  cypress:
    runs-on: ubuntu-latest
    env:
      VITE_GRAPHQL_ENDPOINT: 'https://api--staging.gertrude-app.com/graphql/dashboard'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install pnpm
        uses: pnpm/action-setup@v2
      - name: install deps
        run: pnpm install
      - name: build
        run: make build-dash
      - name: cypress
        uses: cypress-io/github-action@v4.2.0
        with:
          start: pnpm --filter @dash/app preview
          project: dash/app
